name: Bug Report
description: Something about the `Rx` API is not working as expected.
title: "[Bug]: "
labels: ["bug", "untriaged"]
body:
  - type: markdown
    attributes:
      value: |
        Bug reports are very welcome!
        This template will help gather the information needed to start the review process.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please share a clear and concise description of the problem.
        Include the behavior you expect and the behavior you are actually seeing.
      placeholder: Describe your issue.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: |
        Please include minimal steps to reproduce the problem, if possible.
        This could be a code snippet or a small project setup and the steps to run it.
        If possible, please avoid including screenshots.
      placeholder: Reproduction steps (minimal).
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: |
        Please provide what version of the `Rx` API your issue occurs on.
        This can be the commit hash, or a release tag.
    validations:
      required: true
  - type: textarea
    id: regression
    attributes:
      label: Regression?
      description: |
        Did this work in a previous version of the `Rx` API?
        If you can, please point to a version in which this feature was functional to help narrow down the problem.
      placeholder: Leave this field blank if you aren't sure.
    validations:
      required: false
  - type: textarea
    id: potential-causes-and-fixes
    attributes:
      label: Potential Causes and Fixes
      description: |
        Do you already know what could be causing this?
        Any and all hints could be valuable.
        Please provide us with what you know.
      placeholder: Provide potential fixes, if known.
    validations:
      required: false
