blank_issues_enabled: false
contact_links:
  - name: Refunct Community Discord Server
    url: https://discord.gg/refunct
    about: Need help with Refunct-related issues? Join our friendly and helpful community of Refunct speedrunners.
